### ISSUE TITLE
Failed to load settings from /etc/elasticsearch/elasticsearch.yml

### ISSUE THREAD

**Issue by mzac** [spujadas/elk-docker#101]
I have cloned your repo and I am trying to build to add port 514 for syslog however I'm getting this error.  Any ideas?

```
root@photon1 [ ~/downloads/elk-docker ]# cat /etc/photon-release
VMware Photon Linux 1.0
PHOTON_BUILD_NUMBER=13c08b6
```

```
root@photon1 [ ~/downloads/elk-docker ]# docker version
Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64
```

```
root@photon1 [ ~/downloads/elk-docker ]# docker run -it mzac23/elk-pfsense
 * Starting periodic command scheduler cron   [ OK ]
 * Starting Elasticsearch Server
 sysctl: setting key "vm.max_map_count": Read-only file system
Exception in thread "main" SettingsException[Failed to load settings from /etc/elasticsearch/elasticsearch.yml]; nested: AccessDeniedException[/etc/elasticsearch/elasticsearch.yml];
Likely root cause: java.nio.file.AccessDeniedException: /etc/elasticsearch/elasticsearch.yml
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.Files.newByteChannel(Files.java:361)
        at java.nio.file.Files.newByteChannel(Files.java:407)
        at java.nio.file.spi.FileSystemProvider.newInputStream(FileSystemProvider.java:384)
        at java.nio.file.Files.newInputStream(Files.java:152)
        at org.elasticsearch.common.settings.Settings$Builder.loadFromPath(Settings.java:927)
        at org.elasticsearch.node.internal.InternalSettingsPreparer.prepareEnvironment(InternalSettingsPreparer.java:102)
        at org.elasticsearch.bootstrap.Bootstrap.initialEnvironment(Bootstrap.java:230)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121)
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112)
        at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54)
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:96)
        at org.elasticsearch.cli.Command.main(Command.java:62)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82)
Refer to the log for complete error details.
                                                                                                                                                                                                 [fail]
waiting for Elasticsearch to be up (1/30)
waiting for Elasticsearch to be up (2/30)
waiting for Elasticsearch to be up (3/30)
waiting for Elasticsearch to be up (4/30)
waiting for Elasticsearch to be up (5/30)
waiting for Elasticsearch to be up (6/30)
waiting for Elasticsearch to be up (7/30)
waiting for Elasticsearch to be up (8/30)
waiting for Elasticsearch to be up (9/30)
waiting for Elasticsearch to be up (10/30)
waiting for Elasticsearch to be up (11/30)
waiting for Elasticsearch to be up (12/30)
waiting for Elasticsearch to be up (13/30)
waiting for Elasticsearch to be up (14/30)
waiting for Elasticsearch to be up (15/30)
waiting for Elasticsearch to be up (16/30)
waiting for Elasticsearch to be up (17/30)
waiting for Elasticsearch to be up (18/30)
waiting for Elasticsearch to be up (19/30)
waiting for Elasticsearch to be up (20/30)
waiting for Elasticsearch to be up (21/30)
waiting for Elasticsearch to be up (22/30)
waiting for Elasticsearch to be up (23/30)
waiting for Elasticsearch to be up (24/30)
waiting for Elasticsearch to be up (25/30)
waiting for Elasticsearch to be up (26/30)
waiting for Elasticsearch to be up (27/30)
waiting for Elasticsearch to be up (28/30)
waiting for Elasticsearch to be up (29/30)
waiting for Elasticsearch to be up (30/30)
Couln't start Elasticsearch. Exiting.
Elasticsearch log follows below.

```

**Comment by spujadas** [comment]
> `Exception in thread "main" SettingsException[Failed to load settings from /etc/elasticsearch/elasticsearch.yml]; nested: AccessDeniedException[/etc/elasticsearch/elasticsearch.yml];`

The permissions on `/etc/elasticsearch/elasticsearch.yml` are likely incorrect (which is strange btw, should be readable by default when adding the file to the image). What permissions does the file have?

**Comment by mzac** [comment]
```
root@photon1 [ ~/downloads/elk-docker ]# ls -al
total 148
drwxr-x--- 6 root root 4096 Jan 11 20:53 .
drwxr-x--- 3 root root 4096 Jan 11 20:53 ..
drwxr-x--- 8 root root 4096 Jan 12 16:33 .git
-rw-r----- 1 root root   14 Jan 11 20:53 .gitattributes
-rw-r----- 1 root root   23 Jan 11 20:53 .rspec
-rw-r----- 1 root root  177 Jan 11 20:53 02-beats-input.conf
-rw-r----- 1 root root  456 Jan 11 20:53 10-syslog.conf
-rw-r----- 1 root root  113 Jan 11 20:53 11-nginx.conf
-rw-r----- 1 root root  184 Jan 11 20:53 30-output.conf
-rw-r----- 1 root root 5979 Jan 12 16:55 Dockerfile
-rw-r----- 1 root root   87 Jan 11 20:53 Gemfile
-rw-r----- 1 root root  558 Jan 11 20:53 LICENSE
-rw-r----- 1 root root  101 Jan 11 20:53 README-short.txt
-rw-r----- 1 root root 2267 Jan 11 20:53 README.md
-rw-r----- 1 root root  208 Jan 12 17:07 docker-compose.yml
drwxr-x--- 2 root root 4096 Jan 11 20:53 docs
-rw-r----- 1 root root 2217 Jan 11 20:53 elasticsearch-default
-rw-r----- 1 root root 5180 Jan 11 20:53 elasticsearch-init
-rw-r----- 1 root root 2668 Jan 11 20:53 elasticsearch-jvm.options
-rw-r----- 1 root root 3988 Jan 11 20:53 elasticsearch-log4j2.properties
-rw-r----- 1 root root  133 Jan 11 20:53 elasticsearch-logrotate
-rw-r----- 1 root root 3280 Jan 11 20:53 elasticsearch.yml
-rw-r----- 1 root root 2533 Jan 11 20:53 kibana-init
-rw-r----- 1 root root  132 Jan 11 20:53 kibana-logrotate
-rw-r----- 1 root root 4511 Jan 11 20:53 kibana.yml
-rw-r----- 1 root root 1074 Jan 11 20:53 logstash-beats.crt
-rw-r----- 1 root root 1704 Jan 11 20:53 logstash-beats.key
-rw-r----- 1 root root 3793 Jan 11 20:53 logstash-init
-rw-r----- 1 root root  179 Jan 11 20:53 logstash-logrotate
drwxr-x--- 3 root root 4096 Jan 11 20:53 nginx-filebeat
-rw-r----- 1 root root  304 Jan 11 20:53 nginx.pattern
drwxr-x--- 2 root root 4096 Jan 11 20:53 spec
-rw-r----- 1 root root 4775 Jan 11 20:53 start.sh

```

**Comment by spujadas** [comment]
Sorry, I meant: what permissions does the file have in the image?

**Comment by mzac** [comment]
```
root@54ca31d4fe6f:/etc/elasticsearch# ls -al
total 24
drwxr-xr-x  3 root root 4096 Jan 12 16:58 .
drwxr-xr-x  1 root root 4096 Jan 13 19:32 ..
-rw-r----- 20 root root 3280 Jan 11 20:53 elasticsearch.yml
-rw-r----- 18 root root 2668 Jan 11 20:53 jvm.options
-rw-r----- 19 root root 3988 Jan 11 20:53 log4j2.properties
drwxr-xr-x  2 root root 4096 Jan 12 16:56 scripts

```

**Comment by spujadas** [comment]
Yep, needs to be readable by the `elasticsearch` user.
`chmod -R +r /etc/elasticsearch` in your `Dockerfile` after adding the files should do the trick and get things working.

**Comment by mzac** [comment]
Looks like that did it, maybe you could add this to your Dockerfile distro as well?

```
###############################################################################
#                               CONFIGURATION
###############################################################################

### configure Elasticsearch

ADD ./elasticsearch.yml /etc/elasticsearch/elasticsearch.yml
ADD ./elasticsearch-log4j2.properties /etc/elasticsearch/log4j2.properties
ADD ./elasticsearch-jvm.options /etc/elasticsearch/jvm.options
ADD ./elasticsearch-default /etc/default/elasticsearch
RUN chmod -R +r /etc/elasticsearch

```

```
root@photon1 [ ~/downloads/elk-docker ]# docker run -it mzac23/elk-pfsense
 * Starting periodic command scheduler cron                                                                                                                    [ OK ]
 * Starting Elasticsearch Server                                                                                                                                      sysctl: setting key "vm.max_map_count": Read-only file system
                                                                                                                                                               [ OK ]
waiting for Elasticsearch to be up (1/30)
waiting for Elasticsearch to be up (2/30)
waiting for Elasticsearch to be up (3/30)
waiting for Elasticsearch to be up (4/30)
waiting for Elasticsearch to be up (5/30)
waiting for Elasticsearch to be up (6/30)
Waiting for Elasticsearch cluster to respond (1/30)
logstash started.
 * Starting Kibana5                                                                                                                                            [ OK ]
==> /var/log/elasticsearch/elasticsearch.log <==
[2017-01-13T19:50:11,141][INFO ][o.e.p.PluginsService     ] [xpNRhlf] loaded module [transport-netty4]
[2017-01-13T19:50:11,141][INFO ][o.e.p.PluginsService     ] [xpNRhlf] no plugins loaded
[2017-01-13T19:50:13,086][INFO ][o.e.n.Node               ] initialized
[2017-01-13T19:50:13,086][INFO ][o.e.n.Node               ] [xpNRhlf] starting ...
[2017-01-13T19:50:13,260][INFO ][o.e.t.TransportService   ] [xpNRhlf] publish_address {172.17.0.6:9300}, bound_addresses {[::]:9300}
[2017-01-13T19:50:13,264][INFO ][o.e.b.BootstrapCheck     ] [xpNRhlf] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
[2017-01-13T19:50:16,350][INFO ][o.e.c.s.ClusterService   ] [xpNRhlf] new_master {xpNRhlf}{xpNRhlfgRGqQ6ezWNITCmA}{Y_Zy1S0BRauBstchu8evUQ}{172.17.0.6}{172.17.0.6:9300}, reason: zen-disco-elected-as-master ([0] nodes joined)
[2017-01-13T19:50:16,407][INFO ][o.e.h.HttpServer         ] [xpNRhlf] publish_address {172.17.0.6:9200}, bound_addresses {[::]:9200}
[2017-01-13T19:50:16,415][INFO ][o.e.n.Node               ] [xpNRhlf] started
[2017-01-13T19:50:16,424][INFO ][o.e.g.GatewayService     ] [xpNRhlf] recovered [0] indices into cluster_state

==> /var/log/logstash/logstash-plain.log <==

==> /var/log/kibana/kibana5.log <==

==> /var/log/logstash/logstash-plain.log <==
[2017-01-13T19:50:27,452][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/opt/logstash/data/queue"}
[2017-01-13T19:50:27,482][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"b7c48de0-ab78-47a4-8557-09be049efaf0", :path=>"/opt/logstash/data/uuid"}
[2017-01-13T19:50:27,560][ERROR][logstash.agent           ] failed to fetch pipeline configuration {:message=>"Permission denied - /etc/logstash/conf.d/02-beats-input.conf"}

```

**Comment by spujadas** [comment]
Sure thing.
