### ISSUE TITLE
Errors when bringing up the image using docker-compose

### ISSUE THREAD

**Issue by opkorz** [spujadas/elk-docker#104]
Hi,

I was testing out your new image, 5.1.2, but I'm having issues bringing the image up. I'm receiving these errors, which is a bit hard to understand what's happening. I didn't modify anything and just used the docker-compose file recommended by the documentation. I'm using the 5.0.1 and it seems to be working well, we're just trying out the new version to see if it's worth keeping it up to date. I've also read the issues on memory and I have tried it, but it doesn't seem to fix this issue.

```
Attaching to saelk_elk_1
[saelk_elk_1  |[0m  * Starting periodic command scheduler cron
[saelk_elk_1  |[0m    ...done.
[saelk_elk_1  |[0m  * Starting Elasticsearch Server
[saelk_elk_1  |[0m sysctl: setting key "vm.max_map_count": Read-only file system
[saelk_elk_1  |[0m    ...fail!
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (1/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (2/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (3/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (4/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (5/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (6/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (7/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (8/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (9/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (10/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (11/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (12/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (13/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (14/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (15/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (16/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (17/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (18/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (19/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (20/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (21/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (22/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (23/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (24/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (25/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (26/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (27/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (28/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (29/30)
[saelk_elk_1  |[0m waiting for Elasticsearch to be up (30/30)
[saelk_elk_1  |[0m Couln't start Elasticsearch. Exiting.
[saelk_elk_1  |[0m Elasticsearch log follows below.
[saelk_elk_1  |[0m [2017-01-18T00:12:29,161][INFO ][o.e.n.Node               ] [] initializing ...
[saelk_elk_1  |[0m [2017-01-18T00:12:29,185][ERROR][o.e.b.Bootstrap          ] Exception
[saelk_elk_1  |[0m java.lang.IllegalStateException: Failed to created node environment
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m Caused by: java.nio.file.AccessDeniedException: /var/lib/elasticsearch/nodes
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:220) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:249) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	... 11 more
[saelk_elk_1  |[0m [2017-01-18T00:12:29,199][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
[saelk_elk_1  |[0m org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to created node environment
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m Caused by: java.lang.IllegalStateException: Failed to created node environment
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	... 6 more
[saelk_elk_1  |[0m Caused by: java.nio.file.AccessDeniedException: /var/lib/elasticsearch/nodes
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:220) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:249) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	... 6 more
[saelk_elk_1  |[0m [2017-01-18T00:13:22,933][INFO ][o.e.n.Node               ] [] initializing ...
[saelk_elk_1  |[0m [2017-01-18T00:13:22,961][ERROR][o.e.b.Bootstrap          ] Exception
[saelk_elk_1  |[0m java.lang.IllegalStateException: Failed to created node environment
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) [elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m Caused by: java.nio.file.AccessDeniedException: /var/lib/elasticsearch/nodes
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:220) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:249) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	... 11 more
[saelk_elk_1  |[0m [2017-01-18T00:13:22,975][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
[saelk_elk_1  |[0m org.elasticsearch.bootstrap.StartupException: java.lang.IllegalStateException: Failed to created node environment
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:125) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:112) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.SettingCommand.execute(SettingCommand.java:54) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.cli.Command.main(Command.java:88) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:89) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:82) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m Caused by: java.lang.IllegalStateException: Failed to created node environment
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	... 6 more
[saelk_elk_1  |[0m Caused by: java.nio.file.A
ccessDeniedException: /var/lib/elasticsearch/nodes
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107) ~[?:?]
[saelk_elk_1  |[0m 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384) ~[?:?]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createDirectory(Files.java:674) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at java.nio.file.Files.createDirectories(Files.java:767) ~[?:1.8.0_111]
[saelk_elk_1  |[0m 	at org.elasticsearch.env.NodeEnvironment.<init>(NodeEnvironment.java:220) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:249) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.node.Node.<init>(Node.java:229) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap$6.<init>(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:214) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:306) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:121) ~[elasticsearch-5.1.2.jar:5.1.2]
[saelk_elk_1  |[0m 	... 6 more
[saelk_elk_1 exited with code 1
```

**Comment by EwyynTomato** [comment]
Are you using mount volumes?

**Comment by opkorz** [comment]
@EwyynTomato Yes, I am using mounted volumes.

**Comment by EwyynTomato** [comment]
You may want to add suffix :z or :Z to set volume mode so that container have permission on mounted volume, e.g.
"elk-data:/var/lib/elasticsearch:z"

**Comment by opkorz** [comment]
@EwyynTomato  I see, thanks for the suggestion. I'll also try this out, but I think I've figured out my problem. What I did was change permissions on that mounted volume, that fixed my issue, but your solution is neater. Thanks! I'm closing this issue.
