### ISSUE TITLE
Recent error in elasticsearch - received shard failed for target shard

### ISSUE THREAD

**Issue by Cord-Thomas** [spujadas/elk-docker#117]
My ELK container has always started with the warning:  setting key "fs.file-max": Read-only file system but still operated.

This week, elasticsearch blew up and I am setting this error which seems to relate to max files open.    Below are some details on settings - how best to address?   thank you

[2017-03-02 22:57:53,457][WARN ][cluster.action.shard     ] [Squidboy] [journal-12-res-uranus-2017.02.09][0] received shard failed for target shard [[journal-12-res-uranus-2017.02.09][0], node[kxNhlTVuSwOnaStdoH4tuA], [P], v[3], s[INITIALIZING], a[id=ezDCvcpJQlKfW7guW7dfag], unassigned_info[[reason=CLUSTER_RECOVERED], at[2017-03-02T22:57:28.302Z]]], indexUUID [zCPXCCmgQT2Kq7QmfY8tAA], message [failed recovery], failure [IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to open reader on writer]; nested: FileSystemException[/var/lib/elasticsearch/elasticsearch/nodes/0/indices/journal-12-res-uranus-2017.02.09/0/index/_a_Lucene50_0.tim: **Too many open files**]; ]
[journal-12-res-uranus-2017.02.09][[journal-12-res-uranus-2017.02.09][0]] IndexShardRecoveryException[failed to recovery from gateway]; nested: EngineCreationFailureException[failed to open reader on writer]; nested: FileSystemException[/var/lib/elasticsearch/elasticsearch/nodes/0/indices/journal-12-res-uranus-2017.02.09/0/index/_a_Lucene50_0.tim: Too many open files];
	at org.elasticsearch.index.shard.StoreRecoveryService.recoverFromStore(StoreRecoveryService.java:250)
	at org.elasticsearch.index.shard.StoreRecoveryService.access$100(StoreRecoveryService.java:56)

from container:

'# cat /proc/sys/fs/file-max
65536
'# ulimit -Hn
4096
'# ulimit -Sn
1024
'# sysctl -w fs.file-max=100000
sysctl: setting key "fs.file-max": Read-only file system

from host system:

'# ulimit -n
100000
'# ulimit -n
100000
'# ulimit -Hn
100000
'# ulimit -Sn
100000
'# cat /proc/sys/fs/file-max
65536

**Comment by spujadas** [comment]
It seems that the the maximum number of open files (65536) is insufficient in your set-up.

Could you bump this number up (say `ulimit -n 250000`, see [here](http://queirozf.com/entries/elasticsearch-too-many-open-files) and [here](http://stackoverflow.com/a/15906257/2654646) for alternatives) on your _host_, start the container (you'll still get the warning from Elasticsearch, I need to take care of that), check that the change has been taken into account by browsing to http://localhost:9200/_cluster/nodes?process (see https://github.com/elastic/elasticsearch/issues/3183#issuecomment-19440356), and see how it goes?

**Comment by spujadas** [comment]
Commit https://github.com/spujadas/elk-docker/commit/96a04bba3df2660206470aab3c611a8175a86063 should ensure that you no longer get the warning when ES starts up.

**Comment by Cord-Thomas** [comment]
Thank you - new to docker - i was not aware you had to change host settings first.  Updating setting in /etc/sysconfig/docker worked for me - for some reason, my OPTIONS was set to 1024:4096.  I likely have an outdated version.

**Comment by spujadas** [comment]
Hey no problem! I think that some of these system-level settings are troublesome even for seasoned Docker users 😉
