### ISSUE TITLE
Unable to create file /var/log/elasticsearch/elasticsearch.log java.io.IOException: Permission denied

### ISSUE THREAD

**Issue by hzxGitHub** [spujadas/elk-docker#142]
I first "sudo docker run -it docker_elk bash",then "gosu elasticsearch /opt/elasticsearch/bin/elasticsearch \
    -Edefault.path.logs=/var/log/elasticsearch \
    -Edefault.path.data=/var/lib/elasticsearch \
    -Edefault.path.conf=/etc/elasticsearch".
But I got the error:
2017-06-02 01:45:51,774 main ERROR Unable to create file /var/log/elasticsearch/elasticsearch.log java.io.IOException: Permission denied
	at java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.io.File.createNewFile(File.java:1012)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:574)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:554)
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:112)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:114)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:155)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:131)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:60)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:117)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:84)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)

2017-06-02 01:45:51,781 main ERROR Unable to inject fields into builder class for plugin type class org.apache.logging.log4j.core.appender.RollingFileAppender, element 
RollingFile. java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@4f83df68] unab
le to create manager for [/var/log/elasticsearch/elasticsearch.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@6cf0e0ba[pa
ttern=/var/log/elasticsearch/elasticsearch-%d{yyyy-MM-dd}.log, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[TimeBasedTrigge
ringPolicy(nextRolloverMillis=0, interval=1, modulate=true)]), strategy=DefaultRolloverStrategy(min=1, max=7, useMax=true), advertiseURI=null, layout=[%d{ISO8601}][%-5p
][%-25c{1.}] %marker%.10000m%n]]
	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:114)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:114)
	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:155)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:131)
	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:60)
	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:952)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:892)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:884)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:508)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:232)
	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:244)
	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:545)
	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:261)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:117)
	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:84)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326)
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123)
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122)
	at org.elasticsearch.cli.Command.main(Command.java:88)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84)

2017-06-02 01:45:51,783 main ERROR Unable to invoke factory method in class class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile. ja
--More--(16%)

Looking for your help.
Thanks very much!

**Comment by hzxGitHub** [comment]
I do "chmod 777 /var/log/elasticsearch/" and "chmod 777 /var/lib/elasticsearch/" ,and got:
[2017-06-02T07:27:41,163][INFO ][o.e.n.Node               ] [] initializing ...
[2017-06-02T07:27:41,357][INFO ][o.e.e.NodeEnvironment    ] [xhFuEPT] using [1] data paths, mounts [[/var/lib/elasticsearch (/dev/mapper/vg_zabbixserver-lv_root)]], net usable_space [8.7gb], net total_space [36.8gb], spins? [possibly], types [ext4]
[2017-06-02T07:27:41,362][INFO ][o.e.e.NodeEnvironment    ] [xhFuEPT] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-06-02T07:27:41,364][INFO ][o.e.n.Node               ] node name [xhFuEPT] derived from node ID [xhFuEPTQRZ2EIh9b_13sGg]; set [node.name] to override
[2017-06-02T07:27:41,364][INFO ][o.e.n.Node               ] version[5.4.0], pid[281], build[780f8c4/2017-04-28T17:43:27.229Z], OS[Linux/3.10.5-3.el6.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_121/25.121-b13]
[2017-06-02T07:27:43,064][INFO ][o.e.p.PluginsService     ] [xhFuEPT] loaded module [aggs-matrix-stats]
[2017-06-02T07:27:43,068][INFO ][o.e.p.PluginsService     ] [xhFuEPT] loaded module [ingest-common]
[2017-06-02T07:27:43,068][INFO ][o.e.p.PluginsService     ] [xhFuEPT] loaded module [lang-expression]
[2017-06-02T07:27:43,068][INFO ][o.e.p.PluginsService     ] [xhFuEPT] loaded module [lang-groovy]
[2017-06-02T07:27:43,069][INFO ][o.e.p.PluginsService     ] [xhFuEPT] loaded module [lang-mustache]
[2017-06-02T07:27:43,069][INFO ][o.e.p.PluginsService     ] [xhFuEPT] loaded module [lang-painless]
[2017-06-02T07:27:43,069][INFO ][o.e.p.PluginsService     ] [xhFuEPT] loaded module [percolator]
[2017-06-02T07:27:43,070][INFO ][o.e.p.PluginsService     ] [xhFuEPT] loaded module [reindex]
[2017-06-02T07:27:43,070][INFO ][o.e.p.PluginsService     ] [xhFuEPT] loaded module [transport-netty3]
[2017-06-02T07:27:43,070][INFO ][o.e.p.PluginsService     ] [xhFuEPT] loaded module [transport-netty4]
[2017-06-02T07:27:43,074][INFO ][o.e.p.PluginsService     ] [xhFuEPT] no plugins loaded
[2017-06-02T07:27:46,141][INFO ][o.e.d.DiscoveryModule    ] [xhFuEPT] using discovery type [zen]
[2017-06-02T07:27:47,369][INFO ][o.e.n.Node               ] initialized
[2017-06-02T07:27:47,369][INFO ][o.e.n.Node               ] [xhFuEPT] starting ...
[2017-06-02T07:27:47,658][INFO ][o.e.t.TransportService   ] [xhFuEPT] publish_address {172.17.0.5:9300}, bound_addresses {[::]:9300}
[2017-06-02T07:27:47,672][INFO ][o.e.b.BootstrapChecks    ] [xhFuEPT] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
ERROR: bootstrap checks failed
max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]
[2017-06-02T07:27:47,686][INFO ][o.e.n.Node               ] [xhFuEPT] stopping ...
[2017-06-02T07:27:47,717][INFO ][o.e.n.Node               ] [xhFuEPT] stopped
[2017-06-02T07:27:47,717][INFO ][o.e.n.Node               ] [xhFuEPT] closing ...
[2017-06-02T07:27:47,737][INFO ][o.e.n.Node               ] [xhFuEPT] closed

I noticed "max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]".So I modify the file /etc/security/limits.conf in the virtual machine where the docker is running on.

* soft nofile 65536
* hard nofile 131072
* soft nproc 2048
* hard nproc 4096

Again, I run a elk docker, I still got the error,"max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]".
Looking for your help.

**Comment by hzxGitHub** [comment]
root@ab27e400989a:/# ulimit -n
1024
root@ab27e400989a:/# ulimit -Hn
4096
root@ab27e400989a:/# ulimit -Sn
1024
I tried to change ulimit in the /etc/init.d/elasticsearch to 65536,
MAX_OPEN_FILES=65536

root@ab27e400989a:/# service elasticsearch start
 * Starting Elasticsearch Server                                                                                                                       /etc/init.d/elasticsearch: line 129: ulimit: open files: cannot modify limit: Operation not permitted

Also, I tried to start elk docker in virtual machine by set MAX_OPEN_FILES 
docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it -e MAX_OPEN_FILES="65536"  --name elk sebp/elk > ~/log.txt

Then,errors again.
* Starting periodic command scheduler cron       ESC[80G ^MESC[74G[ OK ]
 * Starting Elasticsearch Server       ESC[80G /etc/init.d/elasticsearch: line 129: ulimit: open files: cannot modify limit: Operation not permitted
2017-06-02 09:27:32,107 main ERROR Unable to create file /var/log/elasticsearch/elasticsearch.log java.io.IOException: Permission denied
        at java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.io.File.createNewFile(File.java:1012)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:574)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:554)
        at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:112)
        at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:114)
        at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:155)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:131)
        at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:60)
        at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:122)
...

Looking for your help!

**Comment by spujadas** [comment]
> I first "sudo docker run -it docker_elk bash",then "gosu elasticsearch /opt/elasticsearch/bin/elasticsearch 
> -Edefault.path.logs=/var/log/elasticsearch 
> -Edefault.path.data=/var/lib/elasticsearch 
> -Edefault.path.conf=/etc/elasticsearch".
> But I got the error:
> 2017-06-02 01:45:51,774 main ERROR Unable to create file /var/log/elasticsearch/elasticsearch.log java.io.IOException: Permission denied

Can't reproduce, your command works fine on a fresh VM/container on my side.
Pretty sure you attempted this without `gosu` first, which created `root`-owned files in `/var/log/elasticsearch/` that couldn't be overwritten when Elasticsearch is started by the `elasticsearch` user.

But more to the point:

> gosu elasticsearch /opt/elasticsearch/bin/elasticsearch ...

If using `bash`, you should start Elasticsearch using `service elasticsearch start`.
It would however be much better to run Elasticsearch by starting the container normally instead of `bash`ing in.

> max file descriptors [4096] for elasticsearch process is too low, increase to at least [65536]

Depends on how Docker is set up: sometimes and for some resources the container inherits the host's
parameters, sometimes they can be changed inside the container.
My suggestion would be to use `docker`'s `--ulimit` option (https://docs.docker.com/engine/reference/commandline/run/#set-ulimits-in-container-ulimit) to start the container.

**Comment by spujadas** [comment]
Closing this issue as it has been inactive for a few months.
