### ISSUE TITLE
Image run exits with WARN and ERROR.

### ISSUE THREAD

**Issue by Chandra-TechPassionate** [spujadas/elk-docker#155]
Getting the below WARN and ERROR during the image run.
 
waiting for Elasticsearch to be up (29/30)
waiting for Elasticsearch to be up (30/30)
Couln't start Elasticsearch. Exiting.
Elasticsearch log follows below.
**[2017-08-04T19:01:41,366][WARN ][o.e.b.JNANatives         ] unable to install syscall filter:
java.lang.UnsupportedOperationException: seccomp(BOGUS_OPERATION): Operation not permitted**
        at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:309) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:638) ~[elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:215) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:99) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:111) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:351) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:123) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:114) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:67) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:122) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.cli.Command.main(Command.java:88) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:91) [elasticsearch-5.5.0.jar:5.5.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:84) [elasticsearch-5.5.0.jar:5.5.0]
[2017-08-04T19:01:41,726][INFO ][o.e.n.Node               ] [] initializing ...
[2017-08-04T19:01:41,824][INFO ][o.e.e.NodeEnvironment    ] [6egxe0_] using [1] data paths, mounts [[/var/lib/elasticsearch (/dev/mapper/RootVolGroup00-lv_var)]], net usable_space [761mb], net total_space [3.9gb], spins? [possibly], types [xfs]
[2017-08-04T19:01:41,824][INFO ][o.e.e.NodeEnvironment    ] [6egxe0_] heap size [1.9gb], compressed ordinary object pointers [true]
[2017-08-04T19:01:41,826][INFO ][o.e.n.Node               ] node name [6egxe0_] derived from node ID [6egxe0_YRdaIN0nCpsQdZQ]; set [node.name] to override
[2017-08-04T19:01:41,826][INFO ][o.e.n.Node               ] version[5.5.0], pid[74], build[260387d/2017-06-30T23:16:05.735Z], OS[Linux/3.10.0-123.20.1.el7.x86_64/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_131/25.131-b11] [2017-08-04T19:01:41,826][INFO ][o.e.n.Node               ] JVM arguments [-Xms2g, -Xmx2g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+DisableExplicitGC, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -Djdk.io.permissionsUseCanonicalPath=true, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Dlog4j.skipJansi=true, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/opt/elasticsearch]
[2017-08-04T19:01:44,060][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [aggs-matrix-stats]
[2017-08-04T19:01:44,060][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [ingest-common]
[2017-08-04T19:01:44,060][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [lang-expression]
[2017-08-04T19:01:44,060][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [lang-groovy]
[2017-08-04T19:01:44,060][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [lang-mustache]
[2017-08-04T19:01:44,060][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [lang-painless]
[2017-08-04T19:01:44,060][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [parent-join]
[2017-08-04T19:01:44,060][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [percolator]
[2017-08-04T19:01:44,061][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [reindex]
[2017-08-04T19:01:44,061][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [transport-netty3]
[2017-08-04T19:01:44,061][INFO ][o.e.p.PluginsService     ] [6egxe0_] loaded module [transport-netty4]
[2017-08-04T19:01:44,065][INFO ][o.e.p.PluginsService     ] [6egxe0_] no plugins loaded
[2017-08-04T19:01:47,322][INFO ][o.e.d.DiscoveryModule    ] [6egxe0_] using discovery type [zen]
[2017-08-04T19:01:48,336][INFO ][o.e.n.Node               ] initialized
[2017-08-04T19:01:48,336][INFO ][o.e.n.Node               ] [6egxe0_] starting ...
[2017-08-04T19:01:48,613][INFO ][o.e.t.TransportService   ] [6egxe0_] publish_address {172.17.0.2:9300}, bound_addresses {[::]:9300}
[2017-08-04T19:01:48,631][INFO ][o.e.b.BootstrapChecks    ] [6egxe0_] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
**[2017-08-04T19:01:48,641][ERROR][o.e.b.Bootstrap          ] [6egxe0_] node validation exception
[1] bootstrap checks failed
[1]: system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk**
[2017-08-04T19:01:48,724][INFO ][o.e.n.Node               ] [6egxe0_] stopping ...
[2017-08-04T19:01:48,767][INFO ][o.e.n.Node               ] [6egxe0_] stopped
[2017-08-04T19:01:48,767][INFO ][o.e.n.Node               ] [6egxe0_] closing ...
[2017-08-04T19:01:48,782][INFO ][o.e.n.Node               ] [6egxe0_] closed

**Comment by spujadas** [comment]
Could you have a look at https://www.elastic.co/guide/en/elasticsearch/reference/current/system-call-filter-check.html for suggestions on the way to proceed?

**Comment by kgeographer** [comment]
Hello
I am getting a similar error to the above, installing the elk 8.3.3 image into a dev Docker container on a Macbook Pro M1. The above link is broken, but [a similar page](https://www.elastic.co/guide/en/elasticsearch/reference/8.4/_system_call_filter_check.html) indicates this is OS dependent, and says "...you must fix any configuration errors on your system...", which isn't too helpful. What I don't know is which OS? Other services in the container uses Debian-based images (python, postgis) - is that a factor? The elk section of the docker-compose.yml file is this:

```
elk:
    platform: linux/amd64
    image: sebp/elk:8.3.3
    ports:
      - "5601:5601"
      - "9200:9200"
      - "5044:5044"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "MAX_MAP_COUNT=262144"
    volumes:
      - dev-elk-data:/var/lib/elasticsearch
```
Any tips? Thanks
