### ISSUE TITLE
Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1

### ISSUE THREAD

**Issue by witkeyshare** [spujadas/elk-docker#187]
[2018-01-25T11:45:17,291][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/opt/logstash/modules/fb_apache/configuration"}
[2018-01-25T11:45:17,311][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/opt/logstash/modules/netflow/configuration"}
[2018-01-25T11:45:17,424][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.queue", :path=>"/opt/logstash/data/queue"}
[2018-01-25T11:45:17,431][INFO ][logstash.setting.writabledirectory] Creating directory {:setting=>"path.dead_letter_queue", :path=>"/opt/logstash/data/dead_letter_queue"}
[2018-01-25T11:45:17,892][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-01-25T11:45:17,942][INFO ][logstash.agent           ] No persistent UUID file found. Generating new UUID {:uuid=>"9c300b8c-4739-42d8-ae78-111fbbdcbadc", :path=>"/opt/logstash/data/uuid"}
[2018-01-25T11:45:18,692][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.2"}
[2018-01-25T11:45:19,177][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-01-25T11:45:23,805][WARN ][logstash.outputs.elasticsearch] You are using a deprecated config setting "document_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. Document types are being deprecated in Elasticsearch 6.0, and removed entirely in 7.0. You should avoid this feature If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"document_type", :plugin=><LogStash::Outputs::ElasticSearch hosts=>[//localhost], manage_template=>false, index=>"%{[@metadata][beat]}-%{+YYYY.MM.dd}", document_type=>"%{[@metadata][type]}", id=>"2a56072b6454d0ba7b78bace11ccf3e85d45ffb891e70dee6f8018e4dcc8eb7c", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_81cd01f2-a015-4736-92eb-dfea319ec4ca", enable_metric=>true, charset=>"UTF-8">, workers=>1, template_name=>"logstash", template_overwrite=>false, doc_as_upsert=>false, script_type=>"inline", script_lang=>"painless", script_var_name=>"event", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, action=>"index", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>}
[2018-01-25T11:45:24,499][INFO ][logstash.outputs.elasticsearch] Elasticsearch pool URLs updated {:changes=>{:removed=>[], :added=>[http://localhost:9200/]}}
[2018-01-25T11:45:24,512][INFO ][logstash.outputs.elasticsearch] Running health check to see if an Elasticsearch connection is working {:healthcheck_url=>http://localhost:9200/, :path=>"/"}
[2018-01-25T11:45:24,780][WARN ][logstash.outputs.elasticsearch] Restored connection to ES instance {:url=>"http://localhost:9200/"}
[2018-01-25T11:45:24,877][INFO ][logstash.outputs.elasticsearch] ES Output version determined {:es_version=>nil}
[2018-01-25T11:45:24,881][WARN ][logstash.outputs.elasticsearch] Detected a 6.x and above cluster: the `type` event field won't be used to determine the document _type {:es_version=>6}
[2018-01-25T11:45:24,908][INFO ][logstash.outputs.elasticsearch] New Elasticsearch output {:class=>"LogStash::Outputs::ElasticSearch", :hosts=>["//localhost"]}
[2018-01-25T11:45:25,238][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>8, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>1000, :thread=>"#<Thread:0x369b4660 run>"}
[2018-01-25T11:45:25,702][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
[2018-01-25T11:45:25,772][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"main"}
[2018-01-25T11:45:25,852][INFO ][org.logstash.beats.Server] Starting server on port: 5044
[2018-01-25T11:45:25,909][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
[2018-01-25T11:45:45,998][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1280] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:45:46,000][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1280] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:46:46,112][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1301] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:46:46,114][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1301] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:47:46,238][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1320] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:47:46,240][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1320] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:48:46,368][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1400] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:48:46,370][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1400] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:49:46,498][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 10.79.108.54:1425] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:49:46,499][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 10.79.108.54:1425] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:50:46,629][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1430] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:50:46,631][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1430] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:51:46,761][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 10.79.108.54:1460] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:51:46,766][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 10.79.108.54:1460] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:52:46,891][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 10.79.108.54:1556] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:52:46,892][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 10.79.108.54:1556] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:53:47,025][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 10.79.108.54:1697] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:53:47,028][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 10.79.108.54:1697] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:54:47,154][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1788] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:54:47,156][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1788] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:55:47,284][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1851] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:55:47,286][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1851] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:56:47,412][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 10.79.108.54:1922] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:56:47,415][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 10.79.108.54:1922] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:57:47,544][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1958] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:57:47,545][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:1958] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2018-01-25T11:58:47,675][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:2004] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 3
[2018-01-25T11:58:47,679][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: 10.79.108.54:2004] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1

**Comment by spujadas** [comment]
Please provide more background information on how this happened, as per http://elk-docker.readthedocs.io/#reporting-issues

**Comment by chandukreddi** [comment]
I am running into same issue.

My Environment details:
Logstash: 6.1.3
Conf:
input {
    beats {
        port => "5044"
    }
}
# The filter part of this file is commented out to indicate that it is
# optional.
# filter {
#
# }
output {
    stdout { codec => rubydebug }
}

[elk@localhost logstash-6.1.3]$ ./bin/logstash -f /opt/logstash-6.1.3/config/tst.conf

Error:
[elk@localhost logstash-6.1.3]$ ./bin/logstash -f /opt/logstash-6.1.3/config/tst.conf
Sending Logstash's logs to /opt/data/logs which is now configured via log4j2.properties
[2018-02-07T13:25:04,347][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"fb_apache", :directory=>"/opt/logstash-6.1.3/modules/fb_apache/configuration"}
[2018-02-07T13:25:04,358][INFO ][logstash.modules.scaffold] Initializing module {:module_name=>"netflow", :directory=>"/opt/logstash-6.1.3/modules/netflow/configuration"}
[2018-02-07T13:25:04,680][WARN ][logstash.config.source.multilocal] Ignoring the 'pipelines.yml' file because modules or command line options are specified
[2018-02-07T13:25:05,149][INFO ][logstash.runner          ] Starting Logstash {"logstash.version"=>"6.1.3"}
[2018-02-07T13:25:05,617][INFO ][logstash.agent           ] Successfully started Logstash API endpoint {:port=>9600}
[2018-02-07T13:25:08,747][INFO ][logstash.pipeline        ] Starting pipeline {:pipeline_id=>"main", "pipeline.workers"=>3, "pipeline.batch.size"=>125, "pipeline.batch.delay"=>5, "pipeline.max_inflight"=>375, :thread=>"#<Thread:0xa5a08ec run>"}
[2018-02-07T13:25:09,139][INFO ][logstash.inputs.beats    ] Beats inputs: Starting input listener {:address=>"0.0.0.0:5044"}
[2018-02-07T13:25:09,224][INFO ][logstash.pipeline        ] Pipeline started {"pipeline.id"=>"main"}
[2018-02-07T13:25:09,305][INFO ][org.logstash.beats.Server] Starting server on port: 5044
[2018-02-07T13:25:09,354][INFO ][logstash.agent           ] Pipelines running {:count=>1, :pipelines=>["main"]}
[2018-02-07T13:27:12,645][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: elastic_server:60471] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: -12
[2018-02-07T13:27:12,648][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: **elastic_server**:60471] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: -1
[2018-02-07T13:27:20,527][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: filebeat-running-server:31428] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: -12
[2018-02-07T13:27:20,529][INFO ][org.logstash.beats.BeatsHandler] [local: 0.0.0.0:5044, remote: **filebeat-running-server**:31428] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: -1
^C[2018-02-07T13:28:29,856][WARN ][logstash.runner          ] SIGINT received. Shutting down the agent.
[2018-02-07T13:28:34,866][WARN ][logstash.runner          ] Received shutdown signal, but pipeline is still waiting for in-flight events
to be processed. Sending another ^C will force quit Logstash, but this may cause
data loss.
[2018-02-07T13:28:35,121][WARN ][logstash.shutdownwatcher ] {"inflight_count"=>0, "stalling_thread_info"=>{"other"=>[{"thread_id"=>28, "name"=>"[main]<beats", "current_call"=>"[...]/vendor/bundle/jruby/2.3.0/gems/logstash-input-beats-5.0.6-java/lib/logstash/inputs/beats.rb:199:in `run'"}, {"thread_id"=>24, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}, {"thread_id"=>25, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}, {"thread_id"=>26, "name"=>nil, "current_call"=>"[...]/logstash-core/lib/logstash/util/wrapped_synchronous_queue.rb:133:in `initialize'"}]}}
[2018-02-07T13:28:35,141][ERROR][logstash.shutdownwatcher ] The shutdown process appears to be stalled due to busy or blocked plugins. Check the logs for more information.
[2018-02-07T13:28:36,474][INFO ][logstash.pipeline        ] Pipeline terminated {"pipeline.id"=>"main"}

----------------------

I have running file beat in **"filebeat-running-server"** and **elasticsearch** running on  **"elastic_server**" but if you look at my config file I don't mention anywhere to connect elasticsearch server but I see its connecting and also I am getting **Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: -1** for both requests.

can you please help what i am doing wrong here?

**Comment by mcorreafdez** [comment]
I have the same issue. I had tried disabling/enabling SSL security but it always ends up failing. I have tried:

logstash.conf:
```
input {
  beats {
    port => 5044
    ssl => false
  }
}
output {
  elasticsearch {
    hosts => ["http://elk:9200"]
  }
}
```

filebeat.yml:
```
filebeat.prospectors:
- type: log
  paths:
    - "/my_log_path/*log"
output.logstash:
  hosts: ["elk:5044"]
```

But I always get the same error:
```
[2019-02-15T10:42:33,791][INFO ][org.logstash.beats.BeatsHandler] [local: 172.19.0.2:5044, remote: 172.19.0.4:33322] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
[2019-02-15T10:42:33,791][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:392) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:359) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:342) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$300(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.channel.AbstractChannelHandlerContext$4.run(AbstractChannelHandlerContext.java:236) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.18.Final.jar:4.1.18.Final]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 1
        at org.logstash.beats.BeatsParser.decode(BeatsParser.java:92) ~[logstash-input-beats-5.1.6.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
        ... 10 more

```

**Comment by mcorreafdez** [comment]
Starting back again and following https://elk-docker.readthedocs.io/#forwarding-logs-filebeat guide, everything is working as spected.
