### ISSUE TITLE
Invalid Frame Type

### ISSUE THREAD

**Issue by dbrody2004** [spujadas/elk-docker#214]
Getting Invalid Frame Types using docker's syslog driver.   We have several docker containers and seems to happen on all.

sysctl -w vm.max_map_count=262144
docker container run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk_debug elk:debug

docker run --name mysql_debug --env="MYSQL_ROOT_PASSWORD=shelby911" --publish 3306:3306 -d --volume=$MYSQL_DATA:/var/lib/mysql --log-driver=syslog --log-opt syslog-address=tcp://:5044  --log-opt syslog-facility=daemon --log-opt syslog-format=rfc3164 mysql:debug

==> /var/log/logstash/logstash-plain.log <==
[2018-07-26T23:55:20,723][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 172.17.0.4:48510] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 49
[2018-07-26T23:55:20,724][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 49
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:459) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.18.Final.jar:4.1.18.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_171]
Caused by: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 49
	at org.logstash.beats.BeatsParser.decode(BeatsParser.java:92) ~[logstash-input-beats-5.0.16.jar:?]
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-all-4.1.18.Final.jar:4.1.18.Final]
	... 8 more
[2018-07-26T23:55:20,727][INFO ][org.logstash.beats.BeatsHandler] [local: 172.17.0.2:5044, remote: 172.17.0.4:48510] Handling exception: org.logstash.beats.BeatsParser$InvalidFrameProtocolException: Invalid Frame Type, received: 52
[2018-07-26T23:55:20,727][WARN ][io.netty.channel.DefaultChannelPipeline] An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.

**Comment by spujadas** [comment]
The image's default configuration only has the Beats input plugin set up, i.e. supports messages in the Beats format (as generated by Filebeat for instance).
In your case you're pushing syslog messages to a Beats interface, leading to parsing errors.

For your set-up to work I believe you need to change the image's configuration to enable Logstash's syslog input plugin (https://www.elastic.co/guide/en/logstash/current/plugins-inputs-syslog.html), which should be able to process the syslog messages that the other containers are sending it. See https://elk-docker.readthedocs.io/#updating-logstash-configuration for guidance on how to do this.
