### ISSUE TITLE
running for several days , got 'Suppressed: java.lang.IllegalArgumentException'

### ISSUE THREAD

**Issue by lestergyl** [spujadas/elk-docker#220]
**single node elk, kibana can not connect elastic** 
"2018-08-22T02:57:32Z","tags":["warning","elasticsearch","admin"],"pid":296,"message":"No living connections"}
{"type":"log","@timestamp":"2018-08-22T02:57:32Z","tags":["warning","elasticsearch","admin"],"pid":296,"message":"Unable to revive connection: http://localhost:9200/"}
**in elastic log 
got following exception:**
Suppressed: java.lang.IllegalArgumentException: unknown setting [default.path.data] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:344) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:308) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:282) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:135) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.node.Node.<init>(Node.java:339) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.node.Node.<init>(Node.java:252) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.3.0.jar:6.3.0]
                at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.3.0.jar:6.3.0]
                at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.3.0.jar:6.3.0]
                at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.3.0.jar:6.3.0]

**Comment by spujadas** [comment]
> single node elk, kibana can not connect elastic

Can't say for sure, but if it's been running for a few days a common reason is that Elasticsearch ran out of memory. Or could be anything number of reasons, really.

> `Suppressed: java.lang.IllegalArgumentException: unknown setting [default.path.data] please check that any required plugins are installed, or check the breaking changes documentation for removed settings`

No idea where this is coming from. The (obsolete since version 6) `default.path.data` setting is no longer in the _sebp/elk_ image since tag `600-rc1`.
That being said, if there was an exception in the settings causing Elasticsearch to fail, it would fail at start-up time, not after several days.

So no idea, really. There's a fair chance that what you're encountering isn't Docker-specific, so I'd suggest heading over to http://discuss.elastic.co to ask for support.
