### ISSUE TITLE
ElasticSearch Fails to start

### ISSUE THREAD

**Issue by pltaylor** [spujadas/elk-docker#226]
If I do the following command ElasticSearch fails to start.

`sudo docker run -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk`

Starting the container up in bash mode and attempting to start ElasticSearch manually leads to the following logs.
`[2018-09-10T16:02:24,078][WARN ][o.e.b.JNANatives ] unable to install sy scall filter:
java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed 
        at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilt er.java:341) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.ja va:616) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNA Natives.java:258) [elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Native s.java:113) [elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.jav a:109) [elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:171) [elas ticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) [elast icsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136 ) [elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java: 127) [elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwar eCommand.java:86) [elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:1 24) [elasticsearch-cli-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cl i-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) [elasticsearch-6.4.0.jar:6.4.0]
[2018-09-10T16:02:25,082][INFO ][o.e.n.Node ] [] initializing ...
[2018-09-10T16:02:26,946][INFO ][o.e.e.NodeEnvironment ] [8V9tQgO] using [1] data paths, mounts [[/ (rootfs)]], net usable_space [10.1tb], net total_space [1 7.4tb], types [rootfs]
[2018-09-10T16:02:26,947][INFO ][o.e.e.NodeEnvironment ] [8V9tQgO] heap size [990.7mb], compressed ordinary object pointers [true]
[2018-09-10T16:02:26,950][INFO ][o.e.n.Node ] [8V9tQgO] node name derived from node ID [8V9tQgO6R9ySeOLTT0-vpw]; set [node.name] to override
[2018-09-10T16:02:26,952][INFO ][o.e.n.Node ] [8V9tQgO] version[6. 4.0], pid[226], build[default/tar/595516e/2018-08-17T23:18:47.308994Z], OS[Linux /3.10.105/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/1.8.0_181/25.1 81-b13]
[2018-09-10T16:02:26,952][INFO ][o.e.n.Node ] [8V9tQgO] JVM argume nts [-Xms1g, -Xmx1g, -XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction =75, -XX:+UseCMSInitiatingOccupancyOnly, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt .headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFa stThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.ne tty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2 .disable.jmx=true, -Djava.io.tmpdir=/tmp/elasticsearch.M5uh2nFD, -XX:+HeapDumpOn OutOfMemoryError, -XX:HeapDumpPath=data, -XX:ErrorFile=logs/hs_err_pid%p.log, -X X:+PrintGCDetails, -XX:+PrintGCDateStamps, -XX:+PrintTenuringDistribution, -XX:+ PrintGCApplicationStoppedTime, -Xloggc:logs/gc.log, -XX:+UseGCLogFileRotation, - XX:NumberOfGCLogFiles=32, -XX:GCLogFileSize=64m, -Des.path.home=/opt/elasticsear ch, -Des.path.conf=/etc/elasticsearch, -Des.distribution.flavor=default, -Des.di stribution.type=tar]
[2018-09-10T16:02:38,457][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [aggs-matrix-stats]
[2018-09-10T16:02:38,458][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [analysis-common]
[2018-09-10T16:02:38,458][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [ingest-common]
[2018-09-10T16:02:38,459][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [lang-expression]
[2018-09-10T16:02:38,459][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [lang-mustache]
[2018-09-10T16:02:38,461][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [lang-painless]
[2018-09-10T16:02:38,461][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [mapper-extras]
[2018-09-10T16:02:38,462][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [parent-join]
[2018-09-10T16:02:38,463][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [percolator]
[2018-09-10T16:02:38,463][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [rank-eval]
[2018-09-10T16:02:38,464][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [reindex]
[2018-09-10T16:02:38,464][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [repository-url]
[2018-09-10T16:02:38,465][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [transport-netty4]
[2018-09-10T16:02:38,465][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [tribe]
[2018-09-10T16:02:38,466][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-core]
[2018-09-10T16:02:38,466][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-deprecation]
[2018-09-10T16:02:38,466][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-graph]
[2018-09-10T16:02:38,467][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-logstash]
[2018-09-10T16:02:38,468][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-ml]
[2018-09-10T16:02:38,470][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-monitoring]
[2018-09-10T16:02:38,471][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-rollup]
[2018-09-10T16:02:38,471][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-security]
[2018-09-10T16:02:38,472][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-sql]
[2018-09-10T16:02:38,473][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-upgrade]
[2018-09-10T16:02:38,474][INFO ][o.e.p.PluginsService ] [8V9tQgO] loaded module [x-pack-watcher]
[2018-09-10T16:02:38,475][INFO ][o.e.p.PluginsService ] [8V9tQgO] no plugins loaded
[2018-09-10T16:02:49,058][WARN ][o.e.b.ElasticsearchUncaughtExceptionHandler] [] uncaught exception in thread [main]
org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [default.path.logs] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:140) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.4.0.jar:6.4.0]
        at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.4.0.jar:6.4.0]
Caused by: java.lang.IllegalArgumentException: unknown setting [default.path.logs] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:393) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:339) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:311) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:282) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:135) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.4.0.jar:6.4.0]
        at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.4.0.jar:6.4.0]
        ... 6 more
        Suppressed: java.lang.IllegalArgumentException: unknown setting [default.path.conf] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:393) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:339) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:311) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:282) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:135) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.4.0.jar:6.4.0]
                at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.4.0.jar:6.4.0]
        Suppressed: java.lang.IllegalArgumentException: unknown setting [default.path.data] please check that any required plugins are installed, or check the breaking changes documentation for removed settings
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:393) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:339) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:311) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.common.settings.AbstractScopedSettings.validate(AbstractScopedSettings.java:282) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.common.settings.SettingsModule.<init>(SettingsModule.java:135) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.node.Node.<init>(Node.java:343) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.node.Node.<init>(Node.java:256) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Bootstrap$5.<init>(Bootstrap.java:213) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:213) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:326) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:136) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:127) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) ~[elasticsearch-cli-6.4.0.jar:6.4.0]
                at org.elasticsearch.cli.Command.main(Command.java:90) ~[elasticsearch-cli-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) ~[elasticsearch-6.4.0.jar:6.4.0]
                at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:86) ~[elasticsearch-6.4.0.jar:6.4.0]
`

Any ideas on how to address this?

**Comment by spujadas** [comment]
Reminds me of this issue: https://github.com/spujadas/elk-docker/issues/107
Perhaps the ideas there can help.

**Comment by pltaylor** [comment]
Yup, I'm trying to do it on a synology, and the same fix works.  I went ahead and pulled andig/syno-elk and life is digging along now.  Thanks for the help, I appreciate it.
