### ISSUE TITLE
Issue install plugin elasticsearch en sepb/elk

### ISSUE THREAD

**Issue by mepamplona** [spujadas/elk-docker#227]
Hi, I need any help...
I am trying install a plugin using this Dockerfile of the official documentation https://elk-docker.readthedocs.io

> FROM sebp/elk
> 
> ENV ES_HOME /opt/elasticsearch
> WORKDIR ${ES_HOME}
> 
> RUN CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin \
>     install -b ingest-geoip

but I have this error. I check nslookup to artifacts.elastic.co ant I have connection ok. Do you know which is the problem? What I am doing wrong?

osboxes@osboxes:~/Documents/ELK$ docker build -t kaipy/elk .
Sending build context to Docker daemon  3.072kB
Step 1/4 : FROM sebp/elk
 ---> 415660a78986
Step 2/4 : ENV ES_HOME /opt/elasticsearch
 ---> Running in 419e4b2bd708
Removing intermediate container 419e4b2bd708
 ---> b67afc91b2af
Step 3/4 : WORKDIR ${ES_HOME}
Removing intermediate container 902370a48f72
 ---> 5331d324bf57
Step 4/4 : RUN CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin     install -b ingest-geoip
 ---> Running in 7ec84c530877
Exception in thread "main" java.net.UnknownHostException: artifacts.elastic.co
	at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
	at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
	at java.net.Socket.connect(Socket.java:589)
	at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
	at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
	at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
	at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
	at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
	at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
	at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
	at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:162)
	at org.elasticsearch.plugins.InstallPluginCommand.urlExists(InstallPluginCommand.java:352)
	at org.elasticsearch.plugins.InstallPluginCommand.getElasticUrl(InstallPluginCommand.java:314)
	at org.elasticsearch.plugins.InstallPluginCommand.download(InstallPluginCommand.java:254)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:229)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
The command '/bin/sh -c CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin     install -b ingest-geoip' returned a non-zero code: 1

**Comment by spujadas** [comment]
As you can connect from your host but apparently not from the container, two possible causes come to mind:
1) your firewall (e.g. iptables on the host) may need to be configured to allow traffic from the container to be routed,
2) if your outbound Internet traffic goes through a proxy then your Docker/container needs to be configured to use it too.

**Comment by mepamplona** [comment]
Thanks for your tips. Finally the problem was there wasn't connection inside Docker/container because it was using bridge interface by default in Docker.

Steps:
1) I've chose to change the network interface when run the image to use the host's interface, so I have Internet connection:
$ docker run **--net=host** -p 5601:5601 -p 9200:9200 -p 5044:5044 -it --name elk sebp/elk

2) Change the Dockerfile when I install the plugins:
$ docker build --no-cache **--network host** -t sebp/elk:dockerfile .

Maybe this option isn't the best, but my knowledge about iptables in docker is basic.

Thank you so much and congrats for your ELK Stack ;)

**Comment by spujadas** [comment]
Nice workaround + thanks for the kind words!
