### ISSUE TITLE
elasticsearch plugin installation failed

### ISSUE THREAD

**Issue by sergeygalkin** [spujadas/elk-docker#236]
As documented but not working

```
Step 18/21 : ENV ES_HOME /opt/elasticsearch
 ---> Running in d35b23b07e49
 ---> 308a4f8935ab
Removing intermediate container d35b23b07e49
Step 19/21 : WORKDIR ${ES_HOME}
 ---> ba62c96b576f
Removing intermediate container 81bf3c3ea7ee
Step 20/21 : RUN CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin install ingest-geoip
 ---> Running in a3d9066f0198
-> Downloading ingest-geoip from elastic
[=================================================] 100%   
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.reflect.ReflectPermission suppressAccessChecks
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.

Exception in thread "main" java.lang.IllegalStateException: unable to read from standard input; is standard input open and a tty attached?
	at org.elasticsearch.cli.Terminal$SystemTerminal.readText(Terminal.java:168)
	at org.elasticsearch.plugins.PluginSecurity.prompt(PluginSecurity.java:74)
	at org.elasticsearch.plugins.PluginSecurity.confirmPolicyExceptions(PluginSecurity.java:67)
	at org.elasticsearch.plugins.InstallPluginCommand.installPlugin(InstallPluginCommand.java:801)
	at org.elasticsearch.plugins.InstallPluginCommand.install(InstallPluginCommand.java:775)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:231)
	at org.elasticsearch.plugins.InstallPluginCommand.execute(InstallPluginCommand.java:216)
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.MultiCommand.execute(MultiCommand.java:77)
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
	at org.elasticsearch.cli.Command.main(Command.java:90)
	at org.elasticsearch.plugins.PluginCli.main(PluginCli.java:47)
The command '/bin/sh -c CONF_DIR=/etc/elasticsearch gosu elasticsearch bin/elasticsearch-plugin install ingest-geoip' returned a non-zero code: 1

```

**Comment by spujadas** [comment]
Fixed by #237
