### ISSUE TITLE
Grafana 6.1.4 502 error connecting to elasticsearch 7.0.0 datasource

### ISSUE THREAD

**Issue by samcro1967** [spujadas/elk-docker#268]
I updated to the latest version of docker container sebp/elk on 4/17/2019.  Since then I have been unable to get Telegraf to start on my host.  It fails connecting to Elasticsearch.  I also get a 502 error connecting to Elasticsearch from Grafana.  I have removed all containers and images and repulled.  I also dleted all data in mount points to start clean and still am unable to connect.  The only change I am aware of that was made on 4/17/2019 was the upgrade of sebp/elk.

I am out of ideas on what to look at next.

**I am running the following versions:**
Grafana 6.1.4 (docker container)
Elasticsearch 7.0.0
Telegraf is 1.10.3 (runs locally on host)
InfluxDB 1.7.6 (runs locally on host)
Docker 18.09.2
Windows 10.0.17763.437

**From http://localhost:9200 I get** 
{
  "name" : "elk",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "ov0z53EQQRyVr2DmDETqCg",
  "version" : {
    "number" : "7.0.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "b7e28a7",
    "build_date" : "2019-04-05T22:55:32.697037Z",
    "build_snapshot" : false,
    "lucene_version" : "8.0.0",
    "minimum_wire_compatibility_version" : "6.7.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

**Grafana config for Elasticsearch data source config**
![image](https://user-images.githubusercontent.com/2319445/56849898-67715180-68c0-11e9-9d64-efb239a64c87.png)

**Telegraf log:**
2019-04-27T12:31:04Z I! Loaded inputs: win_perf_counters docker
2019-04-27T12:31:04Z I! Loaded aggregators: 
2019-04-27T12:31:04Z I! Loaded processors: 
2019-04-27T12:31:04Z I! Loaded outputs: influxdb elasticsearch
2019-04-27T12:31:04Z I! Tags enabled: host=DESKTOP-1ND49C8
2019-04-27T12:31:04Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"DESKTOP-1ND49C8", Flush Interval:10s
2019-04-27T12:31:04Z I! Elasticsearch version: 7.0.0
2019-04-27T12:31:04Z E! [agent] Failed to connect to output elasticsearch, retrying in 15s, error was 'Elasticsearch failed to create index template telegraf : elastic: Error 400 (Bad Request): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{tags={path_match=tag.*, mapping={ignore_above=512, type=keyword}, match_mapping_type=string}}, {metrics_long={mapping={index=false, type=float}, match_mapping_type=long}}, {metrics_double={mapping={index=false, type=float}, match_mapping_type=double}}, {text_fields={mapping={norms=false}, match=*}}], _all={enabled=false}, properties={@timestamp={type=date}, measurement_name={type=keyword}}}] [type=mapper_parsing_exception]' 
2019-04-27T12:31:19Z I! Elasticsearch version: 7.0.0
2019-04-27T12:31:19Z E! [telegraf] Error running agent: Elasticsearch failed to create index template telegraf : elastic: Error 400 (Bad Request): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{tags={path_match=tag.*, mapping={ignore_above=512, type=keyword}, match_mapping_type=string}}, {metrics_long={mapping={index=false, type=float}, match_mapping_type=long}}, {metrics_double={mapping={index=false, type=float}, match_mapping_type=double}}, {text_fields={mapping={norms=false}, match=*}}], _all={enabled=false}, properties={@timestamp={type=date}, measurement_name={type=keyword}}}] [type=mapper_parsing_exception]
2019-04-27T12:31:40Z I! Loaded inputs: win_perf_counters docker
2019-04-27T12:31:40Z I! Loaded aggregators: 
2019-04-27T12:31:40Z I! Loaded processors: 
2019-04-27T12:31:40Z I! Loaded outputs: influxdb elasticsearch
2019-04-27T12:31:40Z I! Tags enabled: host=DESKTOP-1ND49C8
2019-04-27T12:31:40Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"DESKTOP-1ND49C8", Flush Interval:10s
2019-04-27T12:31:40Z I! Elasticsearch version: 7.0.0
2019-04-27T12:31:40Z E! [agent] Failed to connect to output elasticsearch, retrying in 15s, error was 'Elasticsearch failed to create index template telegraf : elastic: Error 400 (Bad Request): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{tags={path_match=tag.*, mapping={ignore_above=512, type=keyword}, match_mapping_type=string}}, {metrics_long={mapping={index=false, type=float}, match_mapping_type=long}}, {metrics_double={mapping={index=false, type=float}, match_mapping_type=double}}, {text_fields={mapping={norms=false}, match=*}}], _all={enabled=false}, properties={@timestamp={type=date}, measurement_name={type=keyword}}}] [type=mapper_parsing_exception]' 
2019-04-27T12:31:55Z I! Elasticsearch version: 7.0.0
2019-04-27T12:31:55Z E! [telegraf] Error running agent: Elasticsearch failed to create index template telegraf : elastic: Error 400 (Bad Request): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{tags={path_match=tag.*, mapping={ignore_above=512, type=keyword}, match_mapping_type=string}}, {metrics_long={mapping={index=false, type=float}, match_mapping_type=long}}, {metrics_double={mapping={index=false, type=float}, match_mapping_type=double}}, {text_fields={mapping={norms=false}, match=*}}], _all={enabled=false}, properties={@timestamp={type=date}, measurement_name={type=keyword}}}] [type=mapper_parsing_exception]
2019-04-27T12:33:27Z I! Loaded inputs: win_perf_counters docker
2019-04-27T12:33:27Z I! Loaded aggregators: 
2019-04-27T12:33:27Z I! Loaded processors: 
2019-04-27T12:33:27Z I! Loaded outputs: influxdb elasticsearch
2019-04-27T12:33:27Z I! Tags enabled: host=DESKTOP-1ND49C8
2019-04-27T12:33:27Z I! [agent] Config: Interval:10s, Quiet:false, Hostname:"DESKTOP-1ND49C8", Flush Interval:10s
2019-04-27T12:33:27Z I! Elasticsearch version: 7.0.0
2019-04-27T12:33:27Z E! [agent] Failed to connect to output elasticsearch, retrying in 15s, error was 'Elasticsearch failed to create index template telegraf : elastic: Error 400 (Bad Request): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{tags={path_match=tag.*, mapping={ignore_above=512, type=keyword}, match_mapping_type=string}}, {metrics_long={mapping={index=false, type=float}, match_mapping_type=long}}, {metrics_double={mapping={index=false, type=float}, match_mapping_type=double}}, {text_fields={mapping={norms=false}, match=*}}], _all={enabled=false}, properties={@timestamp={type=date}, measurement_name={type=keyword}}}] [type=mapper_parsing_exception]' 
2019-04-27T12:33:42Z I! Elasticsearch version: 7.0.0
2019-04-27T12:33:42Z E! [telegraf] Error running agent: Elasticsearch failed to create index template telegraf : elastic: Error 400 (Bad Request): Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [_default_ : {dynamic_templates=[{tags={path_match=tag.*, mapping={ignore_above=512, type=keyword}, match_mapping_type=string}}, {metrics_long={mapping={index=false, type=float}, match_mapping_type=long}}, {metrics_double={mapping={index=false, type=float}, match_mapping_type=double}}, {text_fields={mapping={norms=false}, match=*}}], _all={enabled=false}, properties={@timestamp={type=date}, measurement_name={type=keyword}}}] [type=mapper_parsing_exception]

**Comment by spujadas** [comment]
No idea, but sounds like your issue is related to Grafana and the upgrade to ELK 7 rather than to the image _per se_.
My advice would be to ask for support from the Elastic forums at http://discuss.elastic.co

**Comment by roskakori** [comment]
The above error log includes this line:

> Error 400 (Bad Request): Failed to parse mapping [_doc]

I encountered a similar issue when simply walking through the "Creating a dummy log entry" section of the documentation with the `sebp/elk:700` image on localhost with macOS 10.14.4 and docker 2.0.0.3.

Running the image with docker-compose and adding a few dummy entries works fine, http://localhost:9200/_search?pretty looks as expected.
However when checking kibana at http://localhost:5601/ I only get an error JSON and the following log entries, which also refer to the `doc` vs `_doc` issue. 

Maybe the default configuration in the docker image needs to be adjusted?

```
elk_1  | [2019-05-07T08:02:20,661][INFO ][o.e.c.m.MetaDataIndexTemplateService] [elk] adding template [kibana_index_template:.kibana] for index patterns [.kibana]
elk_1  | [2019-05-07T08:02:20,707][DEBUG][o.e.a.a.i.m.p.TransportPutMappingAction] [elk] failed to put mappings on indices [[[.kibana_1/EAhmrbuPSGSBYeCwHXu19g]]], type [doc]
elk_1  | java.lang.IllegalArgumentException: Rejecting mapping update to [.kibana_1] as the final mapping would have more than 1 type: [_doc, doc]
elk_1  | 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:449) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:398) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:331) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:315) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:238) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210) [elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142) [elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) [elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) [elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) [elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) [elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) [elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
elk_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
elk_1  | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
elk_1  | [2019-05-07T08:02:20,716][DEBUG][o.e.a.b.TransportShardBulkAction] [elk] [.kibana_1][0] failed to execute bulk item (create) index {[.kibana][doc][config:6.7.0], source[{"config":{"buildNum":1},"type":"config","updated_at":"2019-05-07T08:02:20.644Z"}]}
elk_1  | java.lang.IllegalArgumentException: Rejecting mapping update to [.kibana_1] as the final mapping would have more than 1 type: [_doc, doc]
elk_1  | 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:449) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.index.mapper.MapperService.internalMerge(MapperService.java:398) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.index.mapper.MapperService.merge(MapperService.java:331) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.applyRequest(MetaDataMappingService.java:315) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.metadata.MetaDataMappingService$PutMappingExecutor.execute(MetaDataMappingService.java:238) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.MasterService.executeTasks(MasterService.java:687) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.MasterService.calculateTaskOutputs(MasterService.java:310) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.MasterService.runTasks(MasterService.java:210) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.MasterService$Batcher.run(MasterService.java:142) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.TaskBatcher.runIfNotProcessed(TaskBatcher.java:150) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.cluster.service.TaskBatcher$BatchedTask.run(TaskBatcher.java:188) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.common.util.concurrent.ThreadContext$ContextPreservingRunnable.run(ThreadContext.java:681) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:252) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:215) ~[elasticsearch-7.0.0.jar:7.0.0]
elk_1  | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
elk_1  | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
elk_1  | 	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
```

**Comment by roskakori** [comment]
Maybe this warning from logstash about the deprecated `document_type` setting is also related. It shows when starting up the `sebp/elk` for the first time after the docker pull:
```
elk_1  | ==> /var/log/logstash/logstash-plain.log <==
elk_1  | [2019-05-07T08:30:32,104][WARN ][logstash.outputs.elasticsearch] You are using a deprecated config setting "document_type" set in elasticsearch. Deprecated settings will continue to work, but are scheduled for removal from logstash in the future. Document types are being deprecated in Elasticsearch 6.0, and removed entirely in 7.0. You should avoid this feature If you have any questions about this, please visit the #logstash channel on freenode irc. {:name=>"document_type", :plugin=><LogStash::Outputs::ElasticSearch index=>"%{[@metadata][beat]}-%{+YYYY.MM.dd}", manage_template=>false, id=>"c4ee5abcf701afed0db36d4aa16c4fc10da6a92bbd615d837cccdf2f368b7802", hosts=>[//localhost], document_type=>"%{[@metadata][type]}", enable_metric=>true, codec=><LogStash::Codecs::Plain id=>"plain_74b45e9e-9f58-4a02-b119-9a7f7b762570", enable_metric=>true, charset=>"UTF-8">, workers=>1, template_name=>"logstash", template_overwrite=>false, doc_as_upsert=>false, script_type=>"inline", script_lang=>"painless", script_var_name=>"event", scripted_upsert=>false, retry_initial_interval=>2, retry_max_interval=>64, retry_on_conflict=>1, ilm_enabled=>"auto", ilm_rollover_alias=>"logstash", ilm_pattern=>"{now/d}-000001", ilm_policy=>"logstash-policy", action=>"index", ssl_certificate_verification=>true, sniffing=>false, sniffing_delay=>5, timeout=>60, pool_max=>1000, pool_max_per_route=>100, resurrect_delay=>5, validate_after_inactivity=>10000, http_compression=>false>}
```

**Comment by spujadas** [comment]
@roskakori First of all thanks for your detailed input.

> Maybe this warning from logstash about the deprecated document_type setting is also related.

Fair point, I've removed the corresponding config option and will push it in a bit after I also bump up the version of ELK to 7.0.1.

> However when checking kibana at http://localhost:5601/ I only get an error JSON and the following log entries, which also refer to the doc vs _doc issue.

I don't know if the correction to Elasticsearch's config is related to what you're experiencing as I have never seen the error message that you have: give the new image a shot.
On my end, from a freshly created container (without the `document_type` option), if I create dummy log entries, they show up in both Elasticsearch (http://localhost:9200/_search?pretty) and Kibana (http://localhost:5601/ - see screenshot below) as expected.

![image](https://user-images.githubusercontent.com/930566/57324555-50c0cb00-7108-11e9-8286-1a6781b7e956.png)

**Comment by roskakori** [comment]
> I don't know if the correction to Elasticsearch's config is related to what you're experiencing as I have never seen the error message that you have: give the new image a shot.

Sorry, that was my bad. I still had a Kibana 6.7.0 running installed locally with [homebrew](https://brew.sh/). Strangely enough according to the docker logs the docker-Kibana 7.0 did startup successfully on the docker image and I also did not see any error about the docker port mapping to fail. Simply uninstalling the homebrew-Kibana fixed it (both for the elk:700 and elk:701 image).

Thanks for the quick analysis and update of the config and image.

Sadly my fix won't apply for @samcro1967 as it now turned out to be unrelated.

**Comment by samcro1967** [comment]
My machine died so I thought I would see if newer version are working.  Running Grafana 6.3.5
Elasticsearch 7.3.0 I am seeing error 502.  I am able to get to Kabana and load its hme page via http://localhost:5601.  I can also get to http://localhost:9200.  Here is what it returns:

{
  "name" : "elk",
  "cluster_name" : "elasticsearch",
  "cluster_uuid" : "Oh6gWd-8Sw2mD1xYSD0qDg",
  "version" : {
    "number" : "7.3.0",
    "build_flavor" : "default",
    "build_type" : "tar",
    "build_hash" : "de777fa",
    "build_date" : "2019-07-24T18:30:11.767338Z",
    "build_snapshot" : false,
    "lucene_version" : "8.1.0",
    "minimum_wire_compatibility_version" : "6.8.0",
    "minimum_index_compatibility_version" : "6.0.0-beta1"
  },
  "tagline" : "You Know, for Search"
}

Attached are the last 500 lines of the logs for both the elk and Grafana containers.
