### ISSUE TITLE
elk:740 - PDF-Export of Dashboards does not work

### ISSUE THREAD

**Issue by rflume** [spujadas/elk-docker#306]
Hi, 

I am using the Docker image `sepb/elk:740`.

Just wanted to try out the PDF-Export feature to export my Dashboard so I activated the trial license. However, the export fails with the error message:

```
Unable to generate report
Error: Error spawning Chromium browser: [Error: Protocol error (Target.setDiscoverTargets): Target closed.]
```

The error logs are:
```
{"type":"log","@timestamp":"2019-11-18T11:51:53Z","tags":["reporting","queue-job","info"],"pid":286,"message":"Successfully queued job: k34dcj5v007ya47cac11mezq"}
{"type":"response","@timestamp":"2019-11-18T11:51:53Z","tags":["api"],"pid":286,"method":"post","statusCode":200,"req":{"url":"/api/reporting/generate/printablePdf?jobParams=(browserTimezone%3AEurope%2FBerlin%2Clayout%3A(id%3Aprint)%2CobjectType%3Adashboard%2CrelativeUrls%3A!('%2Fapp%2Fkibana%23%2Fdashboard%2F824c0ca0-b36d-11e9-8c6a-8329322683b9%3F_g%3D(refreshInterval%3A(pause%3A!!t%2Cvalue%3A0)%2Ctime%3A(from%3A!'2019-07-24T10%3A00%3A00.000Z!'%2Cto%3A!'2019-07-29T22%3A30%3A00.000Z!'))%26_a%3D(description%3A!'!'%2Cfilters%3A!!()%2CfullScreenMode%3A!!f%2Coptions%3A(hidePanelTitles%3A!!f%2CuseMargins%3A!!t)%2Cpanels%3A!!((embeddableConfig%3A()%2CgridData%3A(h%3A11%2Ci%3A!'1!'%2Cw%3A28%2Cx%3A0%2Cy%3A0)%2Cid%3A!'3aa72a90-b36a-11e9-8c6a-8329322683b9!'%2CpanelIndex%3A!'1!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!')%2C(embeddableConfig%3A()%2CgridData%3A(h%3A15%2Ci%3A!'2!'%2Cw%3A24%2Cx%3A24%2Cy%3A11)%2Cid%3Aaa0e9090-b369-11e9-8c6a-8329322683b9%2CpanelIndex%3A!'2!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!')%2C(embeddableConfig%3A(mapCenter%3A!!(17.308687886770034%2C-3.5156250000000004)%2CmapZoom%3A2)%2CgridData%3A(h%3A15%2Ci%3A!'3!'%2Cw%3A24%2Cx%3A0%2Cy%3A11)%2Cid%3A!'6ce00730-b369-11e9-8c6a-8329322683b9!'%2CpanelIndex%3A!'3!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!')%2C(embeddableConfig%3A()%2CgridData%3A(h%3A11%2Ci%3A!'4!'%2Cw%3A20%2Cx%3A28%2Cy%3A0)%2Cid%3Ab46bed90-b36d-11e9-8c6a-8329322683b9%2CpanelIndex%3A!'4!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!')%2C(embeddableConfig%3A()%2CgridData%3A(h%3A15%2Ci%3A!'5!'%2Cw%3A24%2Cx%3A0%2Cy%3A26)%2Cid%3A!'05be4bb0-b3c4-11e9-8c6a-8329322683b9!'%2CpanelIndex%3A!'5!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!')%2C(embeddableConfig%3A()%2CgridData%3A(h%3A15%2Ci%3A!'6!'%2Cw%3A24%2Cx%3A24%2Cy%3A26)%2Cid%3Ac0e3b060-b3c4-11e9-8c6a-8329322683b9%2CpanelIndex%3A!'6!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!'))%2Cquery%3A(language%3Akuery%2Cquery%3A!'!')%2CtimeRestore%3A!!t%2Ctitle%3AC2%2CviewMode%3Aview)')%2Ctitle%3AC2)","method":"post","headers":{"host":"localhost:5601","connection":"keep-alive","content-length":"0","origin":"http://localhost:5601","kbn-version":"7.4.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","dnt":"1","content-type":"application/json","accept":"*/*","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,pt;q=0.6"},"remoteAddress":"172.18.0.1","userAgent":"172.18.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":373,"contentLength":9},"message":"POST /api/reporting/generate/printablePdf?jobParams=(browserTimezone%3AEurope%2FBerlin%2Clayout%3A(id%3Aprint)%2CobjectType%3Adashboard%2CrelativeUrls%3A!('%2Fapp%2Fkibana%23%2Fdashboard%2F824c0ca0-b36d-11e9-8c6a-8329322683b9%3F_g%3D(refreshInterval%3A(pause%3A!!t%2Cvalue%3A0)%2Ctime%3A(from%3A!'2019-07-24T10%3A00%3A00.000Z!'%2Cto%3A!'2019-07-29T22%3A30%3A00.000Z!'))%26_a%3D(description%3A!'!'%2Cfilters%3A!!()%2CfullScreenMode%3A!!f%2Coptions%3A(hidePanelTitles%3A!!f%2CuseMargins%3A!!t)%2Cpanels%3A!!((embeddableConfig%3A()%2CgridData%3A(h%3A11%2Ci%3A!'1!'%2Cw%3A28%2Cx%3A0%2Cy%3A0)%2Cid%3A!'3aa72a90-b36a-11e9-8c6a-8329322683b9!'%2CpanelIndex%3A!'1!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!')%2C(embeddableConfig%3A()%2CgridData%3A(h%3A15%2Ci%3A!'2!'%2Cw%3A24%2Cx%3A24%2Cy%3A11)%2Cid%3Aaa0e9090-b369-11e9-8c6a-8329322683b9%2CpanelIndex%3A!'2!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!')%2C(embeddableConfig%3A(mapCenter%3A!!(17.308687886770034%2C-3.5156250000000004)%2CmapZoom%3A2)%2CgridData%3A(h%3A15%2Ci%3A!'3!'%2Cw%3A24%2Cx%3A0%2Cy%3A11)%2Cid%3A!'6ce00730-b369-11e9-8c6a-8329322683b9!'%2CpanelIndex%3A!'3!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!')%2C(embeddableConfig%3A()%2CgridData%3A(h%3A11%2Ci%3A!'4!'%2Cw%3A20%2Cx%3A28%2Cy%3A0)%2Cid%3Ab46bed90-b36d-11e9-8c6a-8329322683b9%2CpanelIndex%3A!'4!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!')%2C(embeddableConfig%3A()%2CgridData%3A(h%3A15%2Ci%3A!'5!'%2Cw%3A24%2Cx%3A0%2Cy%3A26)%2Cid%3A!'05be4bb0-b3c4-11e9-8c6a-8329322683b9!'%2CpanelIndex%3A!'5!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!')%2C(embeddableConfig%3A()%2CgridData%3A(h%3A15%2Ci%3A!'6!'%2Cw%3A24%2Cx%3A24%2Cy%3A26)%2Cid%3Ac0e3b060-b3c4-11e9-8c6a-8329322683b9%2CpanelIndex%3A!'6!'%2Ctype%3Avisualization%2Cversion%3A!'7.4.0!'))%2Cquery%3A(language%3Akuery%2Cquery%3A!'!')%2CtimeRestore%3A!!t%2Ctitle%3AC2%2CviewMode%3Aview)')%2Ctitle%3AC2) 200 373ms - 9.0B"}
{"type":"response","@timestamp":"2019-11-18T11:51:53Z","tags":[],"pid":286,"method":"get","statusCode":200,"req":{"url":"/api/reporting/jobs/list?page=0&ids=k34dcj5v007ya47cac11mezq","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","kbn-system-api":"true","dnt":"1","kbn-version":"7.4.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","content-type":"application/json","accept":"*/*","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,pt;q=0.6"},"remoteAddress":"172.18.0.1","userAgent":"172.18.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":11,"contentLength":9},"message":"GET /api/reporting/jobs/list?page=0&ids=k34dcj5v007ya47cac11mezq 200 11ms - 9.0B"}
{"type":"log","@timestamp":"2019-11-18T11:51:56Z","tags":["reporting","esqueue","queue-worker","info"],"pid":286,"message":"k34ckpm0007ya47cac8pgep6 - Claimed job k34dcj5v007ya47cac11mezq"}
{"type":"log","@timestamp":"2019-11-18T11:51:56Z","tags":["reporting","esqueue","queue-worker","info"],"pid":286,"message":"k34ckpm0007ya47cac8pgep6 - Starting job"}
{"type":"error","@timestamp":"2019-11-18T11:51:56Z","tags":["reporting","printable_pdf","execute","k34dcj5v007ya47cac11mezq","error"],"pid":286,"level":"error","error":{"message":"Error spawning Chromium browser: [Error: Protocol error (Target.setDiscoverTargets): Target closed.]","name":"Error","stack":"Error: Error spawning Chromium browser: [Error: Protocol error (Target.setDiscoverTargets): Target closed.]\n    at Observable.Rx.Observable.create [as _subscribe] (/opt/kibana/x-pack/legacy/plugins/reporting/server/browsers/chromium/driver_factory/index.js:124:24)"},"message":"Error spawning Chromium browser: [Error: Protocol error (Target.setDiscoverTargets): Target closed.]"}
{"type":"error","@timestamp":"2019-11-18T11:51:56Z","tags":["warning","process"],"pid":286,"level":"error","error":{"message":"Error: Protocol error (Target.setDiscoverTargets): Target closed.\n    at Promise (/opt/kibana/node_modules/puppeteer-core/lib/Connection.js:74:56)\n    at new Promise (<anonymous>)\n    at Connection.send (/opt/kibana/node_modules/puppeteer-core/lib/Connection.js:73:12)\n    at Function.create (/opt/kibana/node_modules/puppeteer-core/lib/Browser.js:34:22)\n    at Launcher.launch (/opt/kibana/node_modules/puppeteer-core/lib/Launcher.js:184:37)\n    at module.exports.launch (/opt/kibana/node_modules/puppeteer-core/lib/Puppeteer.js:37:27)\n    at Observable.Rx.Observable.create [as _subscribe] (/opt/kibana/x-pack/legacy/plugins/reporting/server/browsers/chromium/driver_factory/index.js:106:25)\n    at Observable._trySubscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:43:25)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:29:22)\n    at MergeMapOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/mergeMap.js:35:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at TakeOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/take.js:35:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at DoOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/tap.js:29:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at /opt/kibana/node_modules/rxjs/internal/util/subscribeTo.js:22:31","name":"UnhandledPromiseRejectionWarning","stack":"UnhandledPromiseRejectionWarning: Error: Protocol error (Target.setDiscoverTargets): Target closed.\n    at Promise (/opt/kibana/node_modules/puppeteer-core/lib/Connection.js:74:56)\n    at new Promise (<anonymous>)\n    at Connection.send (/opt/kibana/node_modules/puppeteer-core/lib/Connection.js:73:12)\n    at Function.create (/opt/kibana/node_modules/puppeteer-core/lib/Browser.js:34:22)\n    at Launcher.launch (/opt/kibana/node_modules/puppeteer-core/lib/Launcher.js:184:37)\n    at module.exports.launch (/opt/kibana/node_modules/puppeteer-core/lib/Puppeteer.js:37:27)\n    at Observable.Rx.Observable.create [as _subscribe] (/opt/kibana/x-pack/legacy/plugins/reporting/server/browsers/chromium/driver_factory/index.js:106:25)\n    at Observable._trySubscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:43:25)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:29:22)\n    at MergeMapOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/mergeMap.js:35:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at TakeOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/take.js:35:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at DoOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/tap.js:29:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at /opt/kibana/node_modules/rxjs/internal/util/subscribeTo.js:22:31\n    at emitWarning (internal/process/promises.js:81:15)\n    at emitPromiseRejectionWarnings (internal/process/promises.js:120:9)\n    at process._tickCallback (internal/process/next_tick.js:69:34)"},"message":"Error: Protocol error (Target.setDiscoverTargets): Target closed.\n    at Promise (/opt/kibana/node_modules/puppeteer-core/lib/Connection.js:74:56)\n    at new Promise (<anonymous>)\n    at Connection.send (/opt/kibana/node_modules/puppeteer-core/lib/Connection.js:73:12)\n    at Function.create (/opt/kibana/node_modules/puppeteer-core/lib/Browser.js:34:22)\n    at Launcher.launch (/opt/kibana/node_modules/puppeteer-core/lib/Launcher.js:184:37)\n    at module.exports.launch (/opt/kibana/node_modules/puppeteer-core/lib/Puppeteer.js:37:27)\n    at Observable.Rx.Observable.create [as _subscribe] (/opt/kibana/x-pack/legacy/plugins/reporting/server/browsers/chromium/driver_factory/index.js:106:25)\n    at Observable._trySubscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:43:25)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:29:22)\n    at MergeMapOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/mergeMap.js:35:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at TakeOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/take.js:35:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at DoOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/tap.js:29:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at /opt/kibana/node_modules/rxjs/internal/util/subscribeTo.js:22:31"}
{"type":"error","@timestamp":"2019-11-18T11:51:56Z","tags":["warning","process"],"pid":286,"level":"error","error":{"message":"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)","name":"UnhandledPromiseRejectionWarning","stack":"Error: Protocol error (Target.setDiscoverTargets): Target closed.\n    at Promise (/opt/kibana/node_modules/puppeteer-core/lib/Connection.js:74:56)\n    at new Promise (<anonymous>)\n    at Connection.send (/opt/kibana/node_modules/puppeteer-core/lib/Connection.js:73:12)\n    at Function.create (/opt/kibana/node_modules/puppeteer-core/lib/Browser.js:34:22)\n    at Launcher.launch (/opt/kibana/node_modules/puppeteer-core/lib/Launcher.js:184:37)\n    at module.exports.launch (/opt/kibana/node_modules/puppeteer-core/lib/Puppeteer.js:37:27)\n    at Observable.Rx.Observable.create [as _subscribe] (/opt/kibana/x-pack/legacy/plugins/reporting/server/browsers/chromium/driver_factory/index.js:106:25)\n    at Observable._trySubscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:43:25)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:29:22)\n    at MergeMapOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/mergeMap.js:35:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at TakeOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/take.js:35:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at DoOperator.call (/opt/kibana/node_modules/rxjs/internal/operators/tap.js:29:23)\n    at Observable.subscribe (/opt/kibana/node_modules/rxjs/internal/Observable.js:24:22)\n    at /opt/kibana/node_modules/rxjs/internal/util/subscribeTo.js:22:31"},"message":"Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 12)"}
{"type":"response","@timestamp":"2019-11-18T11:52:03Z","tags":[],"pid":286,"method":"get","statusCode":200,"req":{"url":"/api/reporting/jobs/list?page=0&ids=k34dcj5v007ya47cac11mezq","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","kbn-system-api":"true","dnt":"1","kbn-version":"7.4.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","content-type":"application/json","accept":"*/*","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,pt;q=0.6"},"remoteAddress":"172.18.0.1","userAgent":"172.18.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":13,"contentLength":9},"message":"GET /api/reporting/jobs/list?page=0&ids=k34dcj5v007ya47cac11mezq 200 13ms - 9.0B"}
{"type":"response","@timestamp":"2019-11-18T11:52:03Z","tags":[],"pid":286,"method":"get","statusCode":200,"req":{"url":"/api/reporting/jobs/output/k34dcj5v007ya47cac11mezq","method":"get","headers":{"host":"localhost:5601","connection":"keep-alive","kbn-system-api":"true","dnt":"1","kbn-version":"7.4.0","user-agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/78.0.3904.97 Safari/537.36","content-type":"application/json","accept":"*/*","sec-fetch-site":"same-origin","sec-fetch-mode":"cors","referer":"http://localhost:5601/app/kibana","accept-encoding":"gzip, deflate, br","accept-language":"de-DE,de;q=0.9,en-US;q=0.8,en;q=0.7,pt;q=0.6"},"remoteAddress":"172.18.0.1","userAgent":"172.18.0.1","referer":"http://localhost:5601/app/kibana"},"res":{"statusCode":200,"responseTime":12,"contentLength":9},"message":"GET /api/reporting/jobs/output/k34dcj5v007ya47cac11mezq 200 12ms - 9.0B"}
```

Any idea how to solve it? 
Or is the export even possible on trial?

Thanks in advance for looking into it!

**Comment by spujadas** [comment]
I'm afraid I'm going to close this issue, as it is a question on the use of the ELK services that is not specific to this Docker image.
I would recommend seeking guidance from the ELK forums over at https://discuss.elastic.co/.
