### ISSUE TITLE
Future versions of Elasticsearch will require Java 11.  Your Java version does not meet this requirement.

### ISSUE THREAD

**Issue by samcro1967** [spujadas/elk-docker#309]
Starting getting this today.  Upgraded to Docker Desktop 19.03.5 yesterday and did a reset which caused all imaged to be downloaded.  Guessing I am running a new version of ELK as a result.  The container no longer starts.  The log seems to indicate a new version of JAVA is needed.

* Starting periodic command scheduler cron,
   ...done.,
 * Starting Elasticsearch Server,
future versions of Elasticsearch will require Java 11; your Java version from [/usr/lib/jvm/java-8-openjdk-amd64/jre] does not meet this requirement,
Exception in thread "main" java.lang.RuntimeException: starting java failed with [137],
output:,
,
error:,
,
	at org.elasticsearch.tools.launchers.JvmErgonomics.flagsFinal(JvmErgonomics.java:111),
	at org.elasticsearch.tools.launchers.JvmErgonomics.finalJvmOptions(JvmErgonomics.java:79),
	at org.elasticsearch.tools.launchers.JvmErgonomics.choose(JvmErgonomics.java:57),
	at org.elasticsearch.tools.launchers.JvmOptionsParser.main(JvmOptionsParser.java:89),
   ...fail!,

**Comment by spujadas** [comment]
It's just a deprecation warning, Java 8 is still fine for now (I'll update the image to use 11 once it becomes mandatory) and the image really should work as is.

That being said, https://github.com/elastic/elasticsearch/issues/45170#issuecomment-517933995 and https://discuss.elastic.co/t/cant-start-elasticsearch-on-ubuntu-19-10/204353/2 suggest that you're too low on memory to start all the services.

Closing as most likely not an issue with the image itself.
