### ISSUE TITLE
java client API

### ISSUE THREAD

**Issue by gadieichhorn** [spujadas/elk-docker#37]
not sure this is related to your work, 
Is the client installed?
which port is it running on (assume 9200)? also tried with port 9300 

started docker instance on 192.168.99.100
can connect to client on port 9200 and Kebana on port 5601
created some logs as instructed in the docs

both server and client version is 2.3.1 (maven)

```
 <dependency>
            <groupId>org.elasticsearch</groupId>
            <artifactId>elasticsearch</artifactId>
            <version>2.3.1</version>
        </dependency>

```

testing the connection from a java API like so:

```
        Settings settings = Settings.settingsBuilder()
                .put("client.transport.sniff", true)
                .put("client.transport.ignore_cluster_name", true)
                .build();

        this.client = TransportClient.builder().settings(settings).build()
                .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("192.168.99.100"), 9200));

```

getting error on connection

```
INFO: [Yandroth] modules [], plugins [], sites []
Apr 29, 2016 12:08:36 PM org.elasticsearch.client.transport.TransportClientNodesService$SniffNodesSampler$1$1 handleException
INFO: [Yandroth] failed to get local cluster state for {#transport#-1}{192.168.99.100}{192.168.99.100:9200}, disconnecting...
ReceiveTimeoutTransportException[[][192.168.99.100:9200][cluster:monitor/state] request_id [0] timed out after [5002ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

and without the settings

```
        this.client = TransportClient.builder()
                .build()
                .addTransportAddress(new InetSocketTransportAddress(InetAddress.getByName("192.168.99.100"), 9200));

```

slightly different connection error...

```
INFO: [Colonel A
merica] modules [], plugins [], sites []
Apr 29, 2016 12:23:44 PM org.elasticsearch.client.transport.TransportClientNodesService$SimpleNodeSampler doSample
INFO: [Colonel America] failed to get node info for {#transport#-1}{192.168.99.100}{192.168.99.100:9200}, disconnecting...
ReceiveTimeoutTransportException[[][192.168.99.100:9200][cluster:monitor/nodes/liveness] request_id [0] timed out after [5003ms]]
	at org.elasticsearch.transport.TransportService$TimeoutHandler.run(TransportService.java:679)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
```

any help appreciated , thanks.

**Comment by gadieichhorn** [comment]
I resolved this issue by exposing port 9300 in the YML file and run docker compse.


elk:
  build: .
  ports:
    - "5601:5601"
    - "9200:9200"
    - "9300:9300"
    - "5044:5044"
    - "5000:5000"

**Comment by spujadas** [comment]
Thanks for the update, will add a word on this in the documentation if others find themselves in the same kind of situation.
